java_library(
    name = "args",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:com_beust_jcommander",
        "@maven//:com_google_inject_guice",
    ],
)
