java_library(
    name = "args",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//third_party:com_beust_jcommander",
        "//third_party:com_google_inject_guice",
    ],
)
